# Generated by Django 2.2.3 on 2019-07-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
