# Generated by Django 2.2.3 on 2019-07-26 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_subject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.QuestionChoice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='typeOf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.QuestionType', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
