# Generated by Django 2.2.3 on 2019-07-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190726_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='index',
            field=models.FloatField(),
        ),
    ]
